import React from 'react'
import Head from 'next/head'
import Image from 'next/image'

const Frame46Page = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='text-white bg-gradient'>
            <nav className='flex items-center justify-between p-4 border-b'>
                <Image src='/assets/icons/backarrow.svg' alt='' width={20} height={20} />
                <div className='items-center justify-between hidden pl-40 space-x-12 lg:flex'>
                    <div className='flex items-center justify-between space-x-1'>
                        <Image src='/assets/icons/unverified.svg' alt='' width={24} height={24} />
                        <h4>UNVERIFIED</h4>
                    </div>
                    <div className='flex items-center justify-between space-x-1'>
                        <div className='bg-white rounded-full w-max'>
                            <Image src='/assets/icons/users.svg' alt='' width={24} height={24} />
                        </div>
                        <h4>BECOME AN IB</h4>
                    </div>
                    <div className='flex items-center justify-between space-x-1'>
                        <div className='bg-white rounded-full w-max'>
                            <Image src='/assets/icons/users.svg' alt='' width={24} height={24} />
                        </div>
                        <h4>COPY TRADING</h4>
                    </div>
                    <div className='flex items-center justify-between space-x-1'>
                        <Image src='/assets/icons/refresh.svg' alt='' width={24} height={24} />
                        <h4>REFRESH</h4>
                    </div>
                </div>
                <div className='flex items-center justify-between space-x-12'>
                    <div className='flex items-center justify-between space-x-2'>
                        <h4>ENGLISH</h4>
                        <Image src='/assets/icons/dropdown2.svg' alt='' width={15} height={15} />
                    </div>
                    <Image src='/assets/icons/menuicon.svg' alt='' width={24} height={24} />
                </div>
            </nav>
            <div className='relative flex flex-col items-center justify-between px-4 py-16 pb-12 space-y-4 sm:flex-row md:px-16 sm:space-y-0'>
                <div className='bg-[#EB5757] py-3 px-8 rounded-[20px]'>
                    <h3 className='font-extrabold'>LIVE</h3>
                </div>
                <h3 className='text-xl font-bold'>BALANCE</h3>
                <div className='px-6 py-3 border border-white rounded cursor-pointer'>
                    <h3 className='font-bold'>CHANGE LEVERAGE</h3>
                </div>
                {/* <div className='absolute -bottom-5 sm:-bottom-7 left-1/2 sm:border-b'>
                    <h1 className='text-5xl font-bold -translate-x-1/2 sm:text-6xl min-w-max'>100000.00 USD</h1>
                </div> */}
            </div>
            <div className="relative py-8">
                <div className="absolute z-10 p-4 text-5xl font-bold transform -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2 sm:text-6xl min-w-max">100000.00 USD</div>
                <div className="absolute left-0 z-0 hidden w-1/6 h-px bg-white lg:w-1/4 md:block top-1/2"></div>
                <div className="absolute right-0 z-0 hidden w-1/6 h-px bg-white lg:w-1/4 md:block top-1/2"></div>
            </div>
            <div className='flex flex-col items-center justify-between px-4 py-16 space-y-12 md:px-16'>
                <div className='flex flex-col items-start justify-between space-y-2 md:items-center'>
                    <h3 className='text-xl font-bold'>EQUITY:  100000.00 USD  |   MARGIN:  0.00USD</h3>
                    <p className='text-xl'>ACCOUNT:  256900  |   MATCH-TRADER  |  FX LIVE   |    LEVERAGE:  1  :  100</p>
                </div>
                <div className='flex items-center justify-between w-full'>
                    <h3 className='text-xl font-bold'>Credit:  0.00 USD</h3>
                    <h3 className='pl-8 text-xl font-bold text-right'>For withdrawal: 100000.00  USD</h3>
                </div>
                <div className='flex flex-col items-center justify-center w-full space-y-4 lg:space-y-0 lg:space-x-4 lg:flex-row'>
                    <button className='text-lg font-bold border border-[#10B981] rounded bg-[#10B981] min-w-56 w-[295px] py-3'>DEPOSIT</button>
                    <button className='text-lg font-bold border border-[#EF4444] rounded text-[#EF4444] min-w-56 w-[295px] py-3'>WITHDRAW</button>
                    <button className='text-lg font-bold border border-[#355881] rounded text-[#355881] min-w-56 w-[295px] py-3'>INTERNAL TRANSFER</button>
                    <button className='text-lg font-bold border border-[#2F80ED] rounded bg-[#2F80ED] min-w-56 w-[295px] py-3'>GO & TRADE</button>
                </div>
            </div>
            <div className='flex items-center justify-start px-4 pt-8 md:px-16'>
                <button className='text-lg font-bold border border-white rounded-t text-[#EF4444] bg-white px-8 py-3'>PAYMENT HISTORY</button>
                <button className='px-8 py-3 text-lg font-bold border border-white rounded-t'>TRADING HISTORY</button>
            </div>
            <div className='bg-[#2F80ED] p-2 w-16 h-16 flex justify-center items-center rounded-full fixed bottom-24 right-8 cursor-pointer'>
                <Image src='/assets/icons/earphones.svg' alt='' width={28} height={28} className='' />
            </div>
        </div>
        <div className='flex flex-col items-center justify-between px-4 py-16 space-y-24'>
            <div className='flex flex-col items-center justify-between w-full py-4 space-y-3 shadow-lg rounded-xl'>
                <h4 className='font-semibold'>NO RECORDS FOUND IN LAST 7 DAYS</h4>
                <button className='border border-[#2F80ED] rounded py-2 px-6 text-[#2F80ED] font-semibold'>SHOW ALL</button>
            </div>
            <div className='bg-[#2F80ED] pt-0 p-2 w-16 h-16 flex justify-center items-center rounded-full cursor-pointer'>
                <p className='text-5xl text-white'>+</p>
            </div>
            <div className='flex flex-col items-center justify-between pt-8 space-y-6'>
                <h2 className='text-3xl font-semibold text-center'>Download trading platform</h2>
                <div className='flex items-center justify-between space-x-6'>
                    <div className='p-2 border border-black rounded-full'>
                        <Image src='/assets/icons/apple.svg' alt='' width={31} height={31} className='' />
                    </div>
                    <div className='p-2 border border-black rounded-full'>
                        <Image src='/assets/icons/android.svg' alt='' width={31} height={31} className='' />
                    </div>
                    <div className='p-2 border border-black rounded-full'>
                        <Image src='/assets/icons/windows.svg' alt='' width={31} height={31} className='' />
                    </div>
                </div>
                <div className='flex items-center justify-between space-x-2'>
                    <Image src='/assets/icons/copyright.svg' alt='' width={16} height={16} className='' />
                    <h5>MATCH-TRADE</h5>
                </div>
                <p className='text-sm'>Contact us at <a className='text-[#2F80ED]' href="mailto:support@match-trade.com">support@match-trade.com</a> if you encounter any problems  Version: v.0.36.2-1067-master</p>
            </div>
        </div>
      </main>
    </>
  )
}

export default Frame46Page