import Head from 'next/head'
import { useRouter } from 'next/router';


export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold">
         Forex Trade Web Application
        </h1>
        <div className='flex gap-x-4 ml-4 mt-5'>
        <button onClick={() => router.push('/login')} className='block rounded-md bg-green-400 color px-3.5 py-2.5'>
          Goto Login
        </button>
        <button onClick={() => router.push('/frame46')} className='block rounded-md bg-blue-400 color px-3.5 py-2.5'>
          Frame 46
        </button>
        <button onClick={() => router.push('/frame7')} className='block rounded-md bg-blue-400 color px-3.5 py-2.5'>
          Frame 7
        </button>
        </div>
       
      </main>
    </>
  )
}
