import React, {useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Frame54Navbar from '../compounds/Frame54Navbar'
import DownloadTradingFooter from '../molecules/DownloadTradingFooter'
import ProfileDetailsForm from '../molecules/ProfileDetailsForm'
import withAuth from '../utils/authToken'

const ProfilePage = () => {

    const [activeFrame54Tab, setActiveFrame54Tab ] = useState('TRADING COPY')

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='text-white bg-gradient'>
            <Frame54Navbar setActiveFrame54Tab={setActiveFrame54Tab} />
            <div className='flex flex-col items-center justify-between py-16'>
                <h1 className='text-2xl font-bold'>Profile</h1>
            </div>
            <div className='bg-[#2F80ED] z-50 p-2 w-16 h-16 flex justify-center items-center rounded-full fixed bottom-24 right-8 cursor-pointer'>
                <Image src='/assets/icons/earphones.svg' alt='' width={28} height={28} className='' />
            </div>
        </div>
        <div className='flex flex-col items-center justify-between px-4 py-16 space-y-24 md:px-8'>
            <ProfileDetailsForm />
            <DownloadTradingFooter />
        </div>
      </main>
    </>
  )
}

export default withAuth(ProfilePage)