import React, {useState} from 'react'
import Head from 'next/head'
import Frame54Navbar from '../compounds/Frame54Navbar'
import DownloadTradingFooter from '../molecules/DownloadTradingFooter'

import { useForm } from 'react-hook-form';

const Frame48Page = () => {

    const [activeFrame54Tab, setActiveFrame54Tab ] = useState('TRADING COPY')

    const { register, handleSubmit, watch } = useForm();

    const validateRepeatPassword = (value: string) => {
      const newPassword = watch("newPassword", ""); // get the value of the "newPassword" field
      return newPassword === value || console.log("Passwords do not match");
    }

    const onSubmit = (data: any) => {
        console.log(data);
    }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='text-white bg-gradient'>
            <Frame54Navbar setActiveFrame54Tab={setActiveFrame54Tab} />
            <div className='flex flex-col items-center justify-between py-16 space-y-8'>
                <h1 className='text-3xl font-bold'>Security</h1>
                <div className='flex items-center justify-center'>
                    <h3 className='font-medium border-b-2 border-[#D9D9D9] px-12 pb-2'>TWO-FACTOR AUTHORIZATION</h3>
                    <h3 className='font-medium border-b-4 border-[#F4F9FF] px-12 pb-2'>CHANGE PASSWORD</h3>
                </div>
                <h1 className='text-3xl font-bold'>Change User Password</h1>
            </div>
        </div>
        <div className='flex flex-col items-center justify-between px-4 py-16 space-y-24'>
            <form onClick={handleSubmit(onSubmit)} className='flex flex-col items-start justify-between space-y-6 w-full text-[#535353] max-w-[450px] px-8 py-12 shadow-lg rounded-xl'>
                <div className='flex flex-col items-start justify-between w-full space-y-3'>
                    <label className='font-semibold'>Current Password</label>
                    <input type="password" className='font-medium border-b border-[#2F80ED] w-full outline-none' {...register('Old Password', { required: true })}/>
                </div>
                <div className='flex flex-col items-start justify-between w-full space-y-3'>
                    <label className='font-semibold'>New Password</label>
                    <input type="password" className='font-medium border-b border-[#2F80ED] w-full outline-none' {...register('New Password', { required: true, minLength: 8 })}/>
                </div>
                <div className='flex flex-col items-start justify-between w-full space-y-3'>
                    <label className='font-semibold'>Repeat Password</label>
                    {/* <input type="password" className='font-medium border-b border-[#2F80ED] w-full outline-none' {...register('Repeat New Password', { required: true, validate: validateRepeatPassword })}/> */}
                </div>
                <div className='w-full'>
                    <button type='submit' className='w-full bg-[#2F80ED] font-semibold rounded-lg text-white py-4 mt-4'>CHANGE PASSWORD</button>
                </div>
            </form>
            <DownloadTradingFooter />
        </div>
      </main>
    </>
  )
}

export default Frame48Page